In [1]:
import torch
import torch.nn.functional as F
from torch import nn

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()

In [4]:
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [5]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [6]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-1.3970e-09, grad_fn=<MeanBackward0>)

In [7]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
        
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [8]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-1.3762,  0.3367,  0.1143],
        [ 1.0179, -0.1879, -1.0631],
        [ 0.2033, -0.3131,  0.5834],
        [-1.2778,  0.2178,  0.1764],
        [-0.4010,  0.9570, -0.1189]], requires_grad=True)

In [9]:
linear(torch.rand(2, 5))

tensor([[0.4014, 1.4077, 0.0000],
        [2.1011, 0.8098, 0.0000]])

In [10]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[2.4418],
        [2.6908]])