In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [2]:
x = torch.arange(4)
torch.save(x, 'data/x-file')

In [3]:
import os

In [5]:
x2 = torch.load('data/x-file')
x2

tensor([0, 1, 2, 3])

In [6]:
y = torch.zeros(4)
torch.save([x, y], 'data/x-files')
x2, y2 = torch.load('data/x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [7]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'data/mydict')
mydict2 = torch.load('data/mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [8]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.outout = nn.Linear(256, 10)
    
    def forward(self, x):
        return self.outout(F.relu(self.hidden(x)))

In [9]:
net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [10]:
torch.save(net.state_dict(), 'data/mlp.params')

In [13]:
clone = MLP()
clone.load_state_dict(torch.load('data/mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (outout): Linear(in_features=256, out_features=10, bias=True)
)

In [15]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])