In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [2]:
import torch
from torch import nn

In [3]:
torch.device('cpu'), torch.device('cuda:0'), torch.device('cuda:1')

(device(type='cpu'),
 device(type='cuda', index=0),
 device(type='cuda', index=1))

In [4]:
torch.cuda.device_count()

0

In [5]:
def try_gpu(i=0):
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')


def try_all_gpus():
    devices = [torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

In [6]:
try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cpu'), device(type='cpu'), [device(type='cpu')])

In [7]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [9]:
X = torch.ones(2, 3, device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
Y = torch.rand(2, 3, device=try_gpu(1))
Y

tensor([[0.2332, 0.6225, 0.1856],
        [0.8993, 0.9523, 0.0135]])

In [11]:
Z = X.cuda(1)
print(X)
print(Z)

AssertionError: Torch not compiled with CUDA enabled

In [12]:
Y + Z

NameError: name 'Z' is not defined

In [13]:
Z.cuda(1) is Z

NameError: name 'Z' is not defined

In [14]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=try_gpu())
net(X)

tensor([[0.5243],
        [0.5243]], grad_fn=<AddmmBackward0>)

In [15]:
net[0].weight.data.device

device(type='cpu')